spring:
  application:
    name: system

# --------------------------------------------------------------------------------------------
# MySQL Database Configuration:
  datasource:
    url: jdbc:mysql://localhost:3306/airport_db
    username: root
    password: harshil-8705
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# --------------------------------------------------------------------------------------------

# H2-Database Driver Configuration:
#datasource:
#  driver-class-name: org.h2.Driver
#  url: jdbc:h2:mem:testdb
#  username: sa
#  password: ""
#
#jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#  hibernate:
#    ddl-auto: update
#  show-sql: true
#  properties:
#    hibernate:
#      format_sql: true
#
#h2:
#  console:
#    enabled: true
#    path: /h2-console

server:
  port: 9090